### ISSUE TITLE
[Question] Base64 buffer

### ISSUE THREAD

**Issue by HugoCornu** [ruffrey/pnger#1]
Hi,

I was wondering : could a html form send an image to a server in Base64?
When you use pnger in your applications, from where the images are coming and why/how are they in base64?

I'm real new to this. I hope my question makes any sense.

**Comment by ruffrey** [comment]
Definitely...you can google something like "get image upload as HTML" or "clipboard image to base64." Here's an example of how I grabbed a clipboard image from a paste event in chrome (uses angular):

> https://github.com/respoke/apollo/blob/master/public/js/directives/ap-paste.js#L37

Here's an example of using pnger in one of my applications:

> https://github.com/ruffrey/homesec/blob/master/src/index.html#L101

Base64 is has many tradeoffs..it worked with the underlying pnger libraries and it's pretty standard to be able to take a binary image and turn it into a base64 string.

If you're coming from an HTML form, you will need to take the binary uploaded file and turn it into a base64 buffer. Hack Sparrow did an awesome blog post on this:

> http://www.hacksparrow.com/base64-encoding-decoding-in-node-js.html

**Comment by HugoCornu** [comment]
Thanks for your well documented answer!

**Comment by ruffrey** [comment]
FO SHO and good luck!
